#!/usr/bin/env bash
# install a new Nginx web server, and configure it so that /redirect_me is redirecting to another page
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
cp /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/save_default
sed -i '46i\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-enabled/default
/etc/init.d/nginx start
